---
# Install pyenv
- include_tasks: pyenv.yml

# Install Pytho(s)
- include_tasks: global_install.yml

# Install pip packages
- include_tasks: pip_packages.yml

# Change the Python version
- include_tasks: global.yml
