---
- name: Install pyenv
  ansible.builtin.include_tasks:
    file: pyenv.yml

- name: Install Python(s)
  ansible.builtin.include_tasks:
    file: global_install.yml

- name: Install pip packages
  ansible.builtin.include_tasks:
    file: pip_packages.yml
