---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether pyenv is installed
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_user_home }}/.pyenv/bin/pyenv --version"
      register: PYENV_INSTALLED
      changed_when: false

    - name: Make sure pyenv is installed
      ansible.builtin.debug:
        var: PYENV_INSTALLED

    - name: Check whether Python(s) installed by 'pyenv install' command
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_user_home }}/.pyenv/bin/pyenv versions"
      register: PYENV_VERSIONS
      changed_when: false
      when:
        - pyenv_python_installs is defined

    - name: Make sure Pythons(s) installed
      ansible.builtin.assert:
        that:
          - "'{{ item }}' in PYENV_VERSIONS.stdout"
      with_items: "{{ pyenv_python_installs }}"
      when:
        - pyenv_python_installs is defined

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: OS_VERSION
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: OS_VERSION
