---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether pyenv is installed
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/bin/pyenv --version"
      register: pyenv_installed
      changed_when: false

    - name: Make sure pyenv is installed
      ansible.builtin.debug:
        var: pyenv_installed

    - name: Set Python 3.11.4
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.command: |
        bash -c "{{ pyenv_root }}/bin/pyenv local 3.11.4"
      args:
        chdir: "/home/{{ linux_user }}"
      changed_when: false

    - name: Check pip is upgraded
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/versions/3.11.4/bin/pip --version"
      register: pip_upgraded
      changed_when: false

    - name: Make sure pip is upgraded
      ansible.builtin.debug:
        var: pip_upgraded

    - name: Check whether Ansible is installed
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/versions/3.11.4/bin/ansible --version"
      register: ansible_installed
      changed_when: false

    - name: Make sure Ansible is installed
      ansible.builtin.debug:
        var: ansible_installed

    - name: Check whether yamllint is installed
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/versions/3.11.4/bin/yamllint --version"
      register: yamllint_installed
      changed_when: false

    - name: Make sure yamllint is installed
      ansible.builtin.debug:
        var: yamllint_installed

    - name: Set Python 3.8.7
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.command: |
        bash -c "{{ pyenv_root }}/bin/pyenv local 3.8.7"
      args:
        chdir: "/home/{{ linux_user }}"
      changed_when: false

    - name: Check pip is upgraded
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/versions/3.8.7/bin/pip --version"
      register: pip_upgraded
      changed_when: false

    - name: Make sure pip is upgraded
      ansible.builtin.debug:
        var: pip_upgraded

    - name: Check whether Ansible is installed
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/versions/3.8.7/bin/ansible --version"
      register: ansible_installed
      changed_when: false

    - name: Make sure Ansible is installed
      ansible.builtin.debug:
        var: ansible_installed

    - name: Check whether yamllint is installed
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/versions/3.8.7/bin/yamllint --version"
      register: yamllint_installed
      changed_when: false

    - name: Make sure yamllint is installed
      ansible.builtin.debug:
        var: yamllint_installed

    - name: Change the local Python version
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.command: |
        bash -c "{{ pyenv_root }}/bin/pyenv local \"{{ pyenv_local }}\""
      args:
        chdir: "/home/{{ linux_user }}"
      changed_when: false

    - name: Check whether Python(s) installed by 'pyenv install' command
      become: yes
      become_user: "{{ linux_user }}"
      ansible.builtin.shell: |
        bash -c "{{ pyenv_root }}/bin/pyenv versions"
      register: pyenv_versions
      changed_when: false
      when:
        - pyenv_python_installs is defined

    - name: Make sure Pythons(s) installed
      ansible.builtin.assert:
        that:
          - "'{{ item }}' in pyenv_versions.stdout"
      with_items: "{{ pyenv_python_installs }}"
      when:
        - pyenv_python_installs is defined

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
