---
name: build
on: [deployment, push]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install ansible-lint
        run: |
          pip install "ansible-lint[community,yamllint]"

      - name: Install galaxy roles
        run: |
          ansible-galaxy install git+https://github.com/${{ github.repository }},${{ github.sha }}
          ansible-galaxy install git+https://github.com/ansible-roles-matsumura/user.git,4252ccfb3b9d4bc18008f54381a987335da8a947

      - name: Execulte ansible-lint
        run: |
          ansible-lint

      - name: Show ansible-lint version
        run: |
          pip list | grep ansible \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'ansible.* '
          ansible-lint --version

  molecule-centos7:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos7:latest

  molecule-centos8:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos8:latest

  molecule-centos7-user_pythons_global:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos7:latest
      molecule-scenario: user_pythons_global

  molecule-centos8-user_pythons_global:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos8:latest
      molecule-scenario: user_pythons_global

  molecule-centos7-pip_test:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos7:latest
      molecule-scenario: pip_test

  molecule-centos8-pip_test:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos8:latest
      molecule-scenario: pip_test

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@master

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: |
          yamllint --version \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
